from .button_demo import ButtonDemo
from .card_demo import CardDemo
from .checkbox_demo import CheckBoxDemo
from .combobox_demo import ComboBoxDemo
from .drawer_demo import DrawerDemo
from .drop_demo import DropDemo
from .graph_demo import GraphDemo
from .icon_demo import IconDemo
from .image_demo import ImageDemo
from .input_demo import InputDemo
from .overlay_demo import OverlayDemo
from .popup_demo import PopupDemo
from .progress_demo import ProgressDemo
from .slider_demo import SliderDemo
from .spinbox_demo import SpinBoxDemo
from .splashscreen_demo import SplashScreenDemo
from .switch_demo import SwitchDemo
from .tab_demo import TabDemo
from .table_demo import TableDemo
from .tag_demo import TagDemo
