from .button_demo import *
from .card_demo import *
from .checkbox_demo import *
from .combobox_demo import *
from .drawer_demo import *
from .drop_demo import *
from .graph_demo import *
from .icon_demo import *
from .image_demo import *
from .input_demo import *
from .overlay_demo import *
from .popup_demo import *
from .progress_demo import *
from .slider_demo import *
from .spinbox_demo import *
from .splashscreen_demo import *
from .switch_demo import *
from .tab_demo import *
from .table_demo import *
from .tag_demo import *
